apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lockman-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: www.lockmancyber.com
      http:
        paths:
          - path: /api/resnet/
            pathType: Prefix
            backend:
              service:
                name: resnet-classify-service
                port:
                  number: 80
          - path: /api/foolbox/
            pathType: Prefix
            backend:
              service:
                name: foolbox-fgsm-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lockmancyber
                port:
                  number: 80
